### ISSUE TITLE
Music App example request

### ISSUE THREAD

**Issue by MizterB** [SKaplanOfficial/PyXA#8]
As I am learning to use PyXA, I am playing with the Music App to further my knowledge.

One of the things I am struggling with is identifying how to access certain data elements...for example, I would like to get a list of all Apple Music playlists that I have subscribed to.

I see this is provided by the `subscription_playlists()` method in [XAMusicSource](https://skaplanofficial.github.io/PyXA/reference/apps/music.html#PyXA.apps.Music.XAMusicSource)

What I can't seem to derive from the documentation is how to obtain a `XAMusicSource` object.  It's mentioned under "See also" in the [XAMusicApplication](https://skaplanofficial.github.io/PyXA/_modules/PyXA/apps/Music.html#XAMusicApplication).  What does "See also" mean?  How do I get from app -> source -> playlist?

On a whim I tried this: `PyXA.Music().subscription_playlists()` which apparently diverted me into appscript (I had to install the package to continue).  It did give me a list, but the objects looked like `app('/System/Applications/Music.app').sources.ID(64).subscription_playlists.ID(182724)` - they were not PyXA objects (I expected [XAMusicSubscriptionPlaylist](https://skaplanofficial.github.io/PyXA/_modules/PyXA/apps/Music.html#XAMusicSubscriptionPlaylist)).  I seem to have stepped out of the realm of PyXA, which I'm guessing is not correct.

My IDE is VSCode, and I'm trying to use both IntelliSense and the debugger to navigate the API and make sense of things.  But those tools are definitely not uncovering everything I need to solve this puzzle.  I feel like I'm missing some sort of programming pattern.

Is there any guidance you can provide for solving this particular use case, and/or just navigating the API in general?  Thank you for any help or examples you can provide.

**Comment by SKaplanOfficial** [comment]
Hmm... there's a few parts to this, but you've pointed out an issue that I've fixed in the upcoming release and am testing currently. Unfortunately, my mechanism to convert scripting dictionaries to PyXA classes doesn't fully handle all possible variations in SDEF configurations, so more testing is needed to iron out these kinds of problems. A major goal of the next few releases is improving general stability now that the general features are well defined.

The correct (but not currently working) way to do this would be: `PyXA.Music().sources().by_id(64).subscription_playlists()`. The issue here is that source objects are currently instances of [XAMediaSource](https://skaplanofficial.github.io/PyXA/reference/apps/media.html#PyXA.apps.MediaApplicationBase.XAMediaSource), a base class for both Music.app and TV.app source objects which _should_ specialize into an [XAMusicSource](https://skaplanofficial.github.io/PyXA/reference/apps/music.html#PyXA.apps.Music.XAMusicSource) object, but does not.

I don't have a workaround off the top of my head, but keep an eye out for the next release sometime in the next few days.

---

Some general tips / technical info that will help elsewhere:
- PyXA falls back to appscript since it is a more complete event bridge. When you get an output like you did here, you can generally assume that it's because that command format hasn't been implemented in PyXA (yet), or the app you're trying to script isn't supported in PyXA. You can check the appscript documentation for further assistance, but the downside is that you miss out on app-specific documentation.
- Barring other issues, the easiest way to get from app -> x -> y is to use the corresponding [XAList](https://skaplanofficial.github.io/PyXA/reference/xabase.html#PyXA.XABase.XAList) method calls, e.g. in your case (app -> source -> playlist), `app.sources()` will give you a list of all sources, then you can get a list of all playlists of a specific source by calling the `playlists()` method, e.g. `app.sources()[0].playlists()`.
- Each supported application has a corresponding module references, e.g. [the one for Music](https://skaplanofficial.github.io/PyXA/reference/apps/music.html). This should provide all of the information you need to work with the API. I am still working on improving these pages and the documentation overall, so please let me know if you'd like to see any changes!

Thanks again for pointing out these problems!

**Comment by MizterB** [comment]
Thanks - the issue that you mentioned certainly seems to reflect the challenge I'm facing.  By returning the base class, I was never going to see the Music-specific information that I was looking for.  I look forward to testing out the fix when it's ready!

The tips are helpful as well - much appreciated.  The appscript explanation makes sense, except for one thing...how did I get there?  On a whim I tried `PyXA.Music().subscription_playlists()` and I got an appscript result.  But in the documentation, that method isn't available in `XAMusicApplication`.  It's not necessarily an issue...just trying to understand how that worked.

Finally...another "how do I" question...

I would like to get a list of all playlist folders.  I assume that I should be able to filter the list of all playlists by the `special_kind` attribute.  I'm trying like this, but it is failing...

`folders = PyXA.Application("Music").playlists().filter("special_kind", "==", PyXA.apps.MediaApplicationBase.XAMediaApplication.PlaylistKind.FOLDER)`

Is this the wrong approach, of have I encountered another bug?

**Comment by SKaplanOfficial** [comment]
For the appscript question: When you call a nonexistent method on an Application object, PyXA passes the call to appscript. This makes so third-party apps which I haven't specifically programmed support for can still be scripted. I'm planning to add automatic conversion from appscript types to PyXA ones, where possible, but am still exploring how best to do that. In any case, since `subscription_playlists()` doesn't exist on `XAMusicApplication`, your call was passed to appscript since that is (apparently) a valid call that's not defined in Music's scripting dictionary.

For the second part, I'd generally recommend using the by_special_kind() method on the list of playlists, but you'll need a temporary workaround for now -- that method doesn't currently create the proper AppleEvent format due to the conversion challenges I mentioned before.

A temporary workaround is to manually create the event, i.e.:
```python
app = PyXA.Music()
string_value = PyXA.XABase.unOSType(app.PlaylistKind.FOLDER.value)
event_format = PyXA.XAEvents.event_from_str(string_value)
folders = app.playlists().filter("specialKind", "==", event_format)
```

Also, for now, you should use the camelCase format of the property name (this too will be fixed in an upcoming version).

Thanks for uncovering all these problems... 😅

**Comment by MizterB** [comment]
Happy to continue to provide feedback if it's useful.

Regarding your comment about using `by_special_kind()` on the list (when fixed)...I was under the impression that those "by_xxx" methods only returned the first matching item.  How would that work like a filter, where I want a list of all matches?

**Comment by SKaplanOfficial** [comment]
Ah, you're right. Filtering is the way to go if you're trying to get a list of all folder playlists. I'm going to make it easier so that you don't have to manually create the event.

**Comment by MizterB** [comment]
Hi, some more feedback.

If I try to play a specific playlist, Music just resumes playback of the currently selected track.

According to the docs, if I pass a playlist object to `play()` it should play that playlist.  The behavior seems to match the 'no item is provided' logic.

Example 1-liner with random user playlist:
`PyXA.Music().play(PyXA.Music().playlists()[15])`

**Comment by MizterB** [comment]
Also tried some UI scripting to work ground some issues...look like that isn't working for Music?  The Podcast example works fine for me - I can see all the various UI elements under `front_window`.  However, I don't see any of the same inside of Music's `front_window`.

**Comment by SKaplanOfficial** [comment]
Yep, I'm seeing the same issues. I've fixed the `play()` one in the upcoming release, which I'm going to publish later today just to get these fixes to you. I'll look into the UI scripting problem, too, and might be able to include a fix for that today as well. For now, you can use System Events as a workaround, i.e.:

```
PyXA.Application("System Events").application_processes().by_name("Music").windows()[0].ui_elements()
```

**Comment by SKaplanOfficial** [comment]
[Release 0.2.1](https://github.com/SKaplanOfficial/PyXA/releases/tag/v0.2.1) contains fixes for the bugs mentioned here, including the one with UI scripting. Let me know if any of the issues persist.

**Comment by MizterB** [comment]
Wow - fantastic work here, thank you so much for looking into this and turning around fixes so quickly!

Almost everything I mentioned above appears to be fixed...the only thing I still can't seem to do is perform UI scripting on Music without the workaround that you mentioned above.  I'm probably just overlooking the correct entry point.  Could you provide an example of how to get to the top level `UIElementList`?

**Comment by SKaplanOfficial** [comment]
You might be trying to get UI elements of a hidden window, since Music hides when you close it. If you make sure the window is visible first, you can call `ui_elements()` right from the window:

```python
app = PyXA.Music()
app.front_window.visible = True
print(app.front_window.ui_elements())
```

**Comment by MizterB** [comment]
Working now, thanks - honestly, I'm not sure what happened because now I can call it without the `visible` being set.  Previously, with the same calls, it was throwing an error.  If I can recreate and better describe the issue, I'll let you know.

Feel free to close this issue if you'd prefer that I log future findings for Music in a separate one.
